# Site settings
title: CodeFoolz
email: pa.goenka@outlook.com
description: Blog for Java Javascript Golang Openlayers Leaflet.js 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codefoolz.com" # the base hostname & protocol for your site
twitter_username: chikku39
github_username:  pagoenka

# Build settings
markdown: kramdown

highlighter: pygments

paginate: 5

encoding: utf-8

gems: [jekyll-paginate, pygments]